### ISSUE TITLE
Play the music directly instead of writing into a wav file. Please help!

### ISSUE THREAD

**Issue by RED-KAY** [mdoege/PySynth#12]
The title says it all. I want to play the music directly and not write it to a wav file n play. Is there any way?

**Comment by mdoege** [comment]
Which synth are you using? At least for PySynth B/S/E (which use a NumPy array to hold the WAV file data it should be possible). PySynth A OTOH writes to WAV file directly, so it would need more changes.

But for B/S/E, at the end of the make_wav function, the audio data is in the data2 array, so you could put the code from the play_pyaudio function in play_wav.py there, so it will write data2 to a PyAudio stream instead of to a WAV file.

Of course the entire song still will have to render first before audio output begins if you do it that way. So it's not really any better or faster than waiting for the WAV file and playing that.

A better method would be to put PyAudio output in the "for nn, x in enumerate(song):" loop above that, so sound gets fed to PyAudio piecemeal and plays while the rest of the song is still being synthesized.
