### ISSUE TITLE
Why was Python2 Support drop?

### ISSUE THREAD

**Issue by chibill** [mdoege/PySynth#14]
I am slightly confused why python 2 support was dropped when you decided to support python 3?
(Considering its not hard to support both) 

ALso why did you remove the python 2 version from pipy? ( Can't pip install...)

**Comment by mdoege** [comment]
There was urgent user demand for a Python 3 version last year, so I converted the code to Python 3. (And frankly, I just assumed everyone had moved on from Python 2 by then anyway.)

But yes, it would probably not be too difficult to modify the code to also support Python 3 again if there is demand for that now. I am not sure if I can figure out how to fix setup.py, pip, and PyPi so that they work properly for both Python versions, so pull requests are always welcome, especially concerning packaging.

**Comment by mdoege** [comment]
P.S. I've tried the tests, and it looks like the A, B, P, and S synths work fine under Python 2 if you remove the assertion, while C, D, E, and samp are having problems, either crashing or producing wrong output files...

**Comment by chibill** [comment]
And actually on a side note not even the Python 3 version is on PyPi.... 
Only reason I am asking is because I mainly use python 2 because Numpy refuses to work on Windows with Python 3 (crashing with errors that normally happen from wrong bit version (64 vs 32)

And also I remembered this working well on Python 2 last year. (On an IPad with Pythonista.)

Also the possibile reasons for the one she to not work could be the division.

**Comment by mdoege** [comment]
The Python 3 version should be here: https://pypi.python.org/pypi/PySynth

Yes, maybe the bugs are due to divisions somewhere. I think this was the reason I dropped Python 2 support: some scripts worked, some did not, and I could not figure out why. And I did not want to have a Python 2 version that only works partially.

I will look into this some more, but as I said, if there is a pull request that restores Python 2 compatibility for all scripts, I would certainly merge that.

If you are on Windows 10, you could easily install a Linux distro in WSL and run NumPy and PySynth in there.

**Comment by chibill** [comment]
It could be be my python3 install is broken also. 

Can probably close this. (Annoyingly I always use python 2 a lot because it's the default on Debian 8...)

**Comment by mdoege** [comment]
Use Arch Linux instead! 😎

**Comment by mdoege** [comment]
I have now mostly restored Python 2 support in the latest git version. The samp module is the last remaining problem.

I also discovered a strange bug with the note caching in B and E, so all this Python 2 business had some unexpected benefits for Python 3 too. 😀

**Comment by chibill** [comment]
Okay. Thanks! 

I guess my stubbornness actually helped out a project for once. XD

**Comment by mdoege** [comment]
I think it's always better if users say what they want or need. Without any feedback it's hard to know for a developer where the problems are.

**Comment by chibill** [comment]
True.
